import { defineField, defineType } from 'sanity'

// Operation types that can appear in the audit trail
const OPERATION_TYPE_OPTIONS = [
  { title: 'Sale', value: 'SALE' },
  { title: 'Restock', value: 'RESTOCK' },
  { title: 'Cancellation / Return', value: 'CANCELLATION' },
  { title: 'Manual Adjustment', value: 'MANUAL_ADJUSTMENT' },
  { title: 'Reservation', value: 'RESERVATION' },
  { title: 'Reservation Release', value: 'RESERVATION_RELEASE' },
  { title: 'Import', value: 'IMPORT' },
]

// Channel options — same list as on the order schema, plus SYSTEM for automated operations
const CHANNEL_OPTIONS = [
  { title: 'Website', value: 'WEBSITE' },
  { title: 'Instagram DM', value: 'INSTAGRAM' },
  { title: 'WhatsApp', value: 'WHATSAPP' },
  { title: 'Offline / Walk-in', value: 'OFFLINE' },
  { title: 'Other', value: 'OTHER' },
  { title: 'System (Automated)', value: 'SYSTEM' },
]

export const inventoryLogType = defineType({
  name: 'inventoryLog',
  title: 'Inventory Log',
  type: 'document',

  // Studio preview: log ID as title, operationType + channel as subtitle
  preview: {
    select: {
      title: 'logId',
      operationType: 'operationType',
      channel: 'channel',
    },
    prepare({ title, operationType, channel }) {
      const opLabel =
        OPERATION_TYPE_OPTIONS.find((o) => o.value === operationType)?.title ?? operationType ?? '—'
      const chLabel = CHANNEL_OPTIONS.find((o) => o.value === channel)?.title ?? channel ?? '—'
      return {
        title: title || '[[PLACEHOLDER]]',
        subtitle: `${opLabel} · ${chLabel}`,
      }
    },
  },

  fields: [
    // ── Identity ───────────────────────────────────────────────────────────
    defineField({
      name: 'logId',
      title: 'Log ID',
      type: 'string',
      description: 'Unique identifier for this audit log entry. Generated by the backend.',
      validation: (Rule) => Rule.required(),
    }),

    // ── Operation metadata ─────────────────────────────────────────────────
    defineField({
      name: 'operationType',
      title: 'Operation Type',
      type: 'string',
      description: 'The category of inventory change that produced this log entry.',
      options: {
        list: OPERATION_TYPE_OPTIONS,
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'channel',
      title: 'Channel',
      type: 'string',
      description: 'The channel through which this inventory change was triggered.',
      options: {
        list: CHANNEL_OPTIONS,
        layout: 'radio',
      },
    }),

    // ── Product / Variant reference ────────────────────────────────────────
    // Stored as plain strings (not Sanity references) so log entries remain
    // fully intact even if the source product document is later deleted.
    defineField({
      name: 'productId',
      title: 'Product ID',
      type: 'string',
      description: 'Sanity document _id of the affected product at the time of the operation.',
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'productName',
      title: 'Product Name',
      type: 'string',
      description:
        'Snapshot of the product name at operation time. Preserved even if the product is later renamed.',
    }),

    defineField({
      name: 'variantKey',
      title: 'Variant Key',
      type: 'string',
      description:
        'The _key of the specific variant object inside the product document (size+color pair).',
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'size',
      title: 'Size',
      type: 'string',
      description: 'Snapshot of the variant size label (e.g. "UK 9").',
    }),

    defineField({
      name: 'color',
      title: 'Color',
      type: 'string',
      description: 'Snapshot of the variant color label (e.g. "Midnight Black").',
    }),

    // ── Stock delta ────────────────────────────────────────────────────────
    defineField({
      name: 'quantityChange',
      title: 'Quantity Change',
      type: 'number',
      description:
        'How many units changed hands. Negative = stock decreased (sale, reservation). ' +
        'Positive = stock increased (restock, cancellation return).',
      validation: (Rule) =>
        Rule.required()
          .integer()
          .custom((val) => {
            if (val === 0) return 'Quantity change must be non-zero.'
            return true
          }),
    }),

    defineField({
      name: 'stockBefore',
      title: 'Stock Before',
      type: 'number',
      description:
        'Stock level immediately before this operation. May be absent for legacy or import entries.',
      validation: (Rule) => Rule.min(0).integer(),
    }),

    defineField({
      name: 'stockAfter',
      title: 'Stock After',
      type: 'number',
      description: 'Stock level immediately after this operation.',
      validation: (Rule) => Rule.min(0).integer(),
    }),

    // ── Order linkage (optional) ───────────────────────────────────────────
    defineField({
      name: 'orderId',
      title: 'Order ID',
      type: 'string',
      description:
        'The human-readable Order ID (e.g. AWARAA-001234) that triggered this log entry. ' +
        'Empty for manual adjustments or restocks that are not tied to a specific order.',
    }),

    // ── Actor & notes ──────────────────────────────────────────────────────
    defineField({
      name: 'actorNote',
      title: 'Actor Note',
      type: 'string',
      description:
        'Free-text note identifying who or what performed this operation ' +
        '(e.g. "backend-api", "admin:krishna", "import-script-v2").',
    }),

    // ── Timestamp ──────────────────────────────────────────────────────────
    defineField({
      name: 'timestamp',
      title: 'Timestamp',
      type: 'datetime',
      description: 'ISO 8601 timestamp of when the inventory operation occurred.',
      validation: (Rule) => Rule.required(),
    }),
  ],
})
