import { defineField, defineType } from 'sanity'

// Controlled vocabulary for the sales channel — mirrors the channels used by the backend API
const CHANNEL_OPTIONS = [
  { title: 'Website', value: 'WEBSITE' },
  { title: 'Instagram DM', value: 'INSTAGRAM' },
  { title: 'WhatsApp', value: 'WHATSAPP' },
  { title: 'Offline / Walk-in', value: 'OFFLINE' },
  { title: 'Other', value: 'OTHER' },
]

// Order lifecycle states — ordered from earliest to terminal
const STATUS_OPTIONS = [
  { title: 'Inquiry', value: 'INQUIRY' },
  { title: 'Reserved', value: 'RESERVED' },
  { title: 'Confirmed', value: 'CONFIRMED' },
  { title: 'Fulfilled', value: 'FULFILLED' },
  { title: 'Cancelled', value: 'CANCELLED' },
  { title: 'Expired', value: 'EXPIRED' },
  { title: 'Failed', value: 'FAILED' },
  { title: 'Refunded', value: 'REFUNDED' },
  { title: 'Returned', value: 'RETURNED' },
]

// Payment method options — covers online, manual, and offline flows
const PAYMENT_METHOD_OPTIONS = [
  { title: 'Razorpay (Online)', value: 'RAZORPAY' },
  { title: 'Cash on Delivery', value: 'COD' },
  { title: 'UPI Manual', value: 'UPI' },
  { title: 'Bank Transfer', value: 'BANK' },
  { title: 'Other', value: 'OTHER' },
]

// Payment state — separate from order status so reconciliation is straightforward
const PAYMENT_STATUS_OPTIONS = [
  { title: 'Pending', value: 'PENDING' },
  { title: 'Paid', value: 'PAID' },
  { title: 'Failed', value: 'FAILED' },
  { title: 'Refunded', value: 'REFUNDED' },
]

export const orderType = defineType({
  name: 'order',
  title: 'Order',
  type: 'document',

  // Studio preview: human-readable order ID as title, channel + status in subtitle
  preview: {
    select: {
      title: 'orderId',
      channel: 'channel',
      status: 'status',
    },
    prepare({ title, channel, status }) {
      const channelLabel = CHANNEL_OPTIONS.find((o) => o.value === channel)?.title ?? channel ?? '—'
      const statusLabel = STATUS_OPTIONS.find((o) => o.value === status)?.title ?? status ?? '—'
      return {
        title: title || '[[PLACEHOLDER]]',
        subtitle: `${channelLabel} · ${statusLabel}`,
      }
    },
  },

  fields: [
    // ── Identity ───────────────────────────────────────────────────────────
    defineField({
      name: 'orderId',
      title: 'Order ID',
      type: 'string',
      description:
        'Human-readable, unique order number (e.g. AWARAA-001234). Generated by the backend at order creation.',
      validation: (Rule) =>
        Rule.required()
          .regex(/^AWARAA-\d{6}$/)
          .error('Must match the format AWARAA-XXXXXX (six digits).'),
    }),

    // ── Channel & Status ───────────────────────────────────────────────────
    defineField({
      name: 'channel',
      title: 'Sales Channel',
      type: 'string',
      description: 'Where this order originated.',
      options: {
        list: CHANNEL_OPTIONS,
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'status',
      title: 'Order Status',
      type: 'string',
      description: 'Current lifecycle state of the order.',
      options: {
        list: STATUS_OPTIONS,
        layout: 'radio',
      },
      initialValue: 'INQUIRY',
      validation: (Rule) => Rule.required(),
    }),

    // ── Customer ───────────────────────────────────────────────────────────
    defineField({
      name: 'customer',
      title: 'Customer',
      type: 'object',
      description: 'The customer who placed this order.',
      fields: [
        defineField({
          name: 'name',
          title: 'Name',
          type: 'string',
          description: 'Full name of the customer.',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'contact',
          title: 'Contact (Phone / Email)',
          type: 'string',
          description: 'Primary contact number or email address for this order.',
        }),
        defineField({
          name: 'address',
          title: 'Delivery Address',
          type: 'text',
          rows: 3,
          description: 'Full shipping address. Optional for walk-in or offline orders.',
        }),
      ],
      validation: (Rule) => Rule.required(),
    }),

    // ── Line Items ─────────────────────────────────────────────────────────
    // Each element mirrors one variant from the product document. Prices are
    // snapshotted at order time so historical records are never affected by
    // future price changes.
    defineField({
      name: 'items',
      title: 'Order Items',
      type: 'array',
      description: 'One entry per product variant ordered. Prices are snapshotted at order time.',
      of: [
        {
          type: 'object',
          name: 'orderItem',
          fields: [
            defineField({
              name: 'productId',
              title: 'Product ID',
              type: 'string',
              description: 'Sanity document _id of the referenced product.',
            }),
            defineField({
              name: 'productName',
              title: 'Product Name',
              type: 'string',
              description: 'Snapshot of the product name at time of order.',
            }),
            defineField({
              name: 'variantKey',
              title: 'Variant Key',
              type: 'string',
              description: 'The _key of the chosen variant object inside the product document.',
            }),
            defineField({
              name: 'size',
              title: 'Size',
              type: 'string',
            }),
            defineField({
              name: 'color',
              title: 'Color',
              type: 'string',
            }),
            defineField({
              name: 'quantity',
              title: 'Quantity',
              type: 'number',
              validation: (Rule) => Rule.required().min(1).integer(),
            }),
            defineField({
              name: 'unitPrice',
              title: 'Unit Price (₹)',
              type: 'number',
              description: 'Price per unit at time of order.',
              validation: (Rule) => Rule.required().min(0),
            }),
            defineField({
              name: 'totalPrice',
              title: 'Total Price (₹)',
              type: 'number',
              description: 'quantity × unitPrice, computed and stored by the backend.',
              validation: (Rule) => Rule.required().min(0),
            }),
          ],
          preview: {
            select: {
              productName: 'productName',
              size: 'size',
              color: 'color',
              quantity: 'quantity',
              totalPrice: 'totalPrice',
            },
            prepare({ productName, size, color, quantity, totalPrice }) {
              return {
                title: `${productName || 'Unknown product'} — ${size || '?'} / ${color || '?'}`,
                subtitle: `Qty: ${quantity ?? '?'} · ₹${totalPrice ?? '?'}`,
              }
            },
          },
        },
      ],
      validation: (Rule) => Rule.required().min(1).error('An order must have at least one item.'),
    }),

    // ── Financials ─────────────────────────────────────────────────────────
    defineField({
      name: 'totalAmount',
      title: 'Total Amount (₹)',
      type: 'number',
      description: 'Grand total for the order. Should equal the sum of all item totalPrices.',
      validation: (Rule) => Rule.required().min(0),
    }),

    // ── Payment ────────────────────────────────────────────────────────────
    defineField({
      name: 'paymentMethod',
      title: 'Payment Method',
      type: 'string',
      options: {
        list: PAYMENT_METHOD_OPTIONS,
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'paymentStatus',
      title: 'Payment Status',
      type: 'string',
      options: {
        list: PAYMENT_STATUS_OPTIONS,
        layout: 'radio',
      },
      initialValue: 'PENDING',
      validation: (Rule) => Rule.required(),
    }),

    // ── Razorpay IDs (optional — only populated for online payments) ────────
    defineField({
      name: 'razorpayOrderId',
      title: 'Razorpay Order ID',
      type: 'string',
      description:
        'The order_id returned by Razorpay when the payment order was created. Leave blank for non-Razorpay payments.',
    }),

    defineField({
      name: 'razorpayPaymentId',
      title: 'Razorpay Payment ID',
      type: 'string',
      description: 'The payment_id returned by Razorpay after a successful capture.',
    }),

    // ── Idempotency & Inventory guards ─────────────────────────────────────
    defineField({
      name: 'idempotencyKey',
      title: 'Idempotency Key',
      type: 'string',
      description:
        'A unique key generated by the client before submission. Prevents duplicate orders ' +
        'if the same request is retried (e.g. network timeout). Set by the backend; do not edit manually.',
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'inventoryDecremented',
      title: 'Inventory Decremented?',
      type: 'boolean',
      description:
        'Set to true by the backend once stock has been successfully decremented for all items. ' +
        'Prevents double-decrement on retries.',
      initialValue: false,
    }),

    // ── Internal notes ─────────────────────────────────────────────────────
    defineField({
      name: 'notes',
      title: 'Notes',
      type: 'text',
      rows: 4,
      description: 'Optional internal notes about this order (e.g. special requests, customer messages).',
    }),

    // ── Timestamps ─────────────────────────────────────────────────────────
    // These are set by the backend API, not the Sanity Studio UI.
    defineField({
      name: 'createdAt',
      title: 'Created At',
      type: 'datetime',
      description: 'ISO 8601 timestamp of when the order was first created.',
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'updatedAt',
      title: 'Updated At',
      type: 'datetime',
      description: 'ISO 8601 timestamp of the last mutation on this document.',
    }),
  ],
})
